--------------------------------------------------------
-- Archivo creado  - domingo-septiembre-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_INFORME
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "INVENTARIO"."TBL_INFORME" 
   (	"CODIEMPL" NUMBER, 
	"NOMBEMPL" VARCHAR2(150 BYTE), 
	"CANTIDAD" NUMBER
   ) ON COMMIT PRESERVE ROWS ;
REM INSERTING into INVENTARIO.TBL_INFORME
SET DEFINE OFF;
Insert into INVENTARIO.TBL_INFORME (CODIEMPL,NOMBEMPL,CANTIDAD) values ('1','PEÑA PEÑA EDGAR','1');
Insert into INVENTARIO.TBL_INFORME (CODIEMPL,NOMBEMPL,CANTIDAD) values ('2','ACOSTA AGUILAR MOISES','1');
Insert into INVENTARIO.TBL_INFORME (CODIEMPL,NOMBEMPL,CANTIDAD) values ('3','OJEDA PEREZ CARMEN','1');
Insert into INVENTARIO.TBL_INFORME (CODIEMPL,NOMBEMPL,CANTIDAD) values ('4','GARCIA RAMOS ANA','1');
Insert into INVENTARIO.TBL_INFORME (CODIEMPL,NOMBEMPL,CANTIDAD) values ('5','PORTUGAL NEYRA OSCAR','1');
Insert into INVENTARIO.TBL_INFORME (CODIEMPL,NOMBEMPL,CANTIDAD) values ('6','VELARDE CHAVEZ JESUS','1');
Insert into INVENTARIO.TBL_INFORME (CODIEMPL,NOMBEMPL,CANTIDAD) values ('7','RIVERA CARDENAS MARTIN','1');
Insert into INVENTARIO.TBL_INFORME (CODIEMPL,NOMBEMPL,CANTIDAD) values ('8','ALCANTARA ROMERO SUSANA','1');
Insert into INVENTARIO.TBL_INFORME (CODIEMPL,NOMBEMPL,CANTIDAD) values ('9','ZURITA CARO CARLA','1');
