create or replace package EMPLEADO_tapi
is

type EMPLEADO_tapi_rec is record (
PASSEMPL  EMPLEADO.PASSEMPL%type
,CUENEMPL  EMPLEADO.CUENEMPL%type
,NOMBEMPL  EMPLEADO.NOMBEMPL%type
,DNIEMPL  EMPLEADO.DNIEMPL%type
,APELEMPL  EMPLEADO.APELEMPL%type
,ESTEMPL  EMPLEADO.ESTEMPL%type
,APELMATE  EMPLEADO.APELMATE%type
,CODIEMPL  EMPLEADO.CODIEMPL%type
);
type EMPLEADO_tapi_tab is table of EMPLEADO_tapi_rec;

-- insert
procedure ins (
p_PASSEMPL in EMPLEADO.PASSEMPL%type default null 
,p_CUENEMPL in EMPLEADO.CUENEMPL%type
,p_NOMBEMPL in EMPLEADO.NOMBEMPL%type
,p_DNIEMPL in EMPLEADO.DNIEMPL%type
,p_APELEMPL in EMPLEADO.APELEMPL%type
,p_ESTEMPL in EMPLEADO.ESTEMPL%type
,p_APELMATE in EMPLEADO.APELMATE%type
,p_CODIEMPL in EMPLEADO.CODIEMPL%type
);
-- update
procedure upd (
p_PASSEMPL in EMPLEADO.PASSEMPL%type default null 
,p_CUENEMPL in EMPLEADO.CUENEMPL%type
,p_NOMBEMPL in EMPLEADO.NOMBEMPL%type
,p_DNIEMPL in EMPLEADO.DNIEMPL%type
,p_APELEMPL in EMPLEADO.APELEMPL%type
,p_ESTEMPL in EMPLEADO.ESTEMPL%type
,p_APELMATE in EMPLEADO.APELMATE%type
,p_CODIEMPL in EMPLEADO.CODIEMPL%type
);
-- delete
procedure del (
p_DNIEMPL in EMPLEADO.DNIEMPL%type
);
end EMPLEADO_tapi;

/
create or replace package body EMPLEADO_tapi
is
-- insert
procedure ins (
p_PASSEMPL in EMPLEADO.PASSEMPL%type default null 
,p_CUENEMPL in EMPLEADO.CUENEMPL%type
,p_NOMBEMPL in EMPLEADO.NOMBEMPL%type
,p_DNIEMPL in EMPLEADO.DNIEMPL%type
,p_APELEMPL in EMPLEADO.APELEMPL%type
,p_ESTEMPL in EMPLEADO.ESTEMPL%type
,p_APELMATE in EMPLEADO.APELMATE%type
,p_CODIEMPL in EMPLEADO.CODIEMPL%type
) is
begin
insert into EMPLEADO(
PASSEMPL
,CUENEMPL
,NOMBEMPL
,DNIEMPL
,APELEMPL
,ESTEMPL
,APELMATE
,CODIEMPL
) values (
p_PASSEMPL
,p_CUENEMPL
,p_NOMBEMPL
,p_DNIEMPL
,p_APELEMPL
,p_ESTEMPL
,p_APELMATE
,p_CODIEMPL
);end;
-- update
procedure upd (
p_PASSEMPL in EMPLEADO.PASSEMPL%type default null 
,p_CUENEMPL in EMPLEADO.CUENEMPL%type
,p_NOMBEMPL in EMPLEADO.NOMBEMPL%type
,p_DNIEMPL in EMPLEADO.DNIEMPL%type
,p_APELEMPL in EMPLEADO.APELEMPL%type
,p_ESTEMPL in EMPLEADO.ESTEMPL%type
,p_APELMATE in EMPLEADO.APELMATE%type
,p_CODIEMPL in EMPLEADO.CODIEMPL%type
) is
begin
update EMPLEADO set
PASSEMPL = p_PASSEMPL
,CUENEMPL = p_CUENEMPL
,NOMBEMPL = p_NOMBEMPL
,APELEMPL = p_APELEMPL
,ESTEMPL = p_ESTEMPL
,APELMATE = p_APELMATE
,CODIEMPL = p_CODIEMPL
where DNIEMPL = p_DNIEMPL;
end;
-- del
procedure del (
p_DNIEMPL in EMPLEADO.DNIEMPL%type
) is
begin
delete from EMPLEADO
where DNIEMPL = p_DNIEMPL;
end;
end EMPLEADO_tapi;
