CREATE OR REPLACE PACKAGE OFICINA_tapi
IS
type OFICINA_tapi_rec
IS
  record
  (
    NOMBOFIC OFICINA.NOMBOFIC%type ,
    PISOOFIC OFICINA.PISOOFIC%type ,
    CODIOFIC OFICINA.CODIOFIC%type ,
    SEDEOFIC OFICINA.SEDEOFIC%type );
type OFICINA_tapi_tab
IS
  TABLE OF OFICINA_tapi_rec;
  -- insert
  PROCEDURE ins(
      p_NOMBOFIC IN OFICINA.NOMBOFIC%type ,
      p_PISOOFIC IN OFICINA.PISOOFIC%type DEFAULT NULL ,
      p_CODIOFIC IN OFICINA.CODIOFIC%type ,
      p_SEDEOFIC IN OFICINA.SEDEOFIC%type );
  -- update
  PROCEDURE upd(
      p_NOMBOFIC IN OFICINA.NOMBOFIC%type ,
      p_PISOOFIC IN OFICINA.PISOOFIC%type DEFAULT NULL ,
      p_CODIOFIC IN OFICINA.CODIOFIC%type ,
      p_SEDEOFIC IN OFICINA.SEDEOFIC%type );
  -- delete
  PROCEDURE del(
      p_CODIOFIC IN OFICINA.CODIOFIC%type );
END OFICINA_tapi;
/
CREATE OR REPLACE PACKAGE body OFICINA_tapi
IS
  -- insert
  PROCEDURE ins(
      p_NOMBOFIC IN OFICINA.NOMBOFIC%type ,
      p_PISOOFIC IN OFICINA.PISOOFIC%type DEFAULT NULL ,
      p_CODIOFIC IN OFICINA.CODIOFIC%type ,
      p_SEDEOFIC IN OFICINA.SEDEOFIC%type )
  IS
  BEGIN
    INSERT
    INTO OFICINA
      (
        NOMBOFIC ,
        PISOOFIC ,
        CODIOFIC ,
        SEDEOFIC
      )
      VALUES
      (
        p_NOMBOFIC ,
        p_PISOOFIC ,
        p_CODIOFIC ,
        p_SEDEOFIC
      );
  END;
-- update
  PROCEDURE upd
    (
      p_NOMBOFIC IN OFICINA.NOMBOFIC%type ,
      p_PISOOFIC IN OFICINA.PISOOFIC%type DEFAULT NULL ,
      p_CODIOFIC IN OFICINA.CODIOFIC%type ,
      p_SEDEOFIC IN OFICINA.SEDEOFIC%type
    )
  IS
  BEGIN
    UPDATE OFICINA
    SET NOMBOFIC   = p_NOMBOFIC ,
      PISOOFIC     = p_PISOOFIC ,
      SEDEOFIC     = p_SEDEOFIC
    WHERE CODIOFIC = p_CODIOFIC;
  END;
-- del
  PROCEDURE del(
      p_CODIOFIC IN OFICINA.CODIOFIC%type )
  IS
  BEGIN
    DELETE FROM OFICINA WHERE CODIOFIC = p_CODIOFIC;
  END;
END OFICINA_tapi;