create or replace package MOVIMIENTO_tapi
is

type MOVIMIENTO_tapi_rec is record (
OBSEUBIC  MOVIMIENTO.OBSEUBIC%type
,TIPOMOVI  MOVIMIENTO.TIPOMOVI%type
,ESTAMOVI  MOVIMIENTO.ESTAMOVI%type
,FECHMOVI  MOVIMIENTO.FECHMOVI%type
,CODIEQUI  MOVIMIENTO.CODIEQUI%type
,CODIMOVI  MOVIMIENTO.CODIMOVI%type
,CODIEMPL  MOVIMIENTO.CODIEMPL%type
,CODIOFICORIG  MOVIMIENTO.CODIOFICORIG%type
,CODIOFICDEST  MOVIMIENTO.CODIOFICDEST%type
);
type MOVIMIENTO_tapi_tab is table of MOVIMIENTO_tapi_rec;

-- insert
procedure ins (
p_OBSEUBIC in MOVIMIENTO.OBSEUBIC%type default null 
,p_TIPOMOVI in MOVIMIENTO.TIPOMOVI%type
,p_ESTAMOVI in MOVIMIENTO.ESTAMOVI%type
,p_FECHMOVI in MOVIMIENTO.FECHMOVI%type
,p_CODIEQUI in MOVIMIENTO.CODIEQUI%type
,p_CODIMOVI in MOVIMIENTO.CODIMOVI%type
,p_CODIEMPL in MOVIMIENTO.CODIEMPL%type
,p_CODIOFICORIG in MOVIMIENTO.CODIOFICORIG%type
,p_CODIOFICDEST in MOVIMIENTO.CODIOFICDEST%type
);
-- update
procedure upd (
p_OBSEUBIC in MOVIMIENTO.OBSEUBIC%type default null 
,p_TIPOMOVI in MOVIMIENTO.TIPOMOVI%type
,p_ESTAMOVI in MOVIMIENTO.ESTAMOVI%type
,p_FECHMOVI in MOVIMIENTO.FECHMOVI%type
,p_CODIEQUI in MOVIMIENTO.CODIEQUI%type
,p_CODIMOVI in MOVIMIENTO.CODIMOVI%type
,p_CODIEMPL in MOVIMIENTO.CODIEMPL%type
,p_CODIOFICORIG in MOVIMIENTO.CODIOFICORIG%type
,p_CODIOFICDEST in MOVIMIENTO.CODIOFICDEST%type
);
-- delete
procedure del (
p_CODIMOVI in MOVIMIENTO.CODIMOVI%type
,p_CODIEQUI in MOVIMIENTO.CODIEQUI%type
,p_CODIEMPL in MOVIMIENTO.CODIEMPL%type
,p_CODIOFICORIG in MOVIMIENTO.CODIOFICORIG%type
,p_CODIOFICDEST in MOVIMIENTO.CODIOFICDEST%type
);
end MOVIMIENTO_tapi;

/
create or replace package body MOVIMIENTO_tapi
is
-- insert
procedure ins (
p_OBSEUBIC in MOVIMIENTO.OBSEUBIC%type default null 
,p_TIPOMOVI in MOVIMIENTO.TIPOMOVI%type
,p_ESTAMOVI in MOVIMIENTO.ESTAMOVI%type
,p_FECHMOVI in MOVIMIENTO.FECHMOVI%type
,p_CODIEQUI in MOVIMIENTO.CODIEQUI%type
,p_CODIMOVI in MOVIMIENTO.CODIMOVI%type
,p_CODIEMPL in MOVIMIENTO.CODIEMPL%type
,p_CODIOFICORIG in MOVIMIENTO.CODIOFICORIG%type
,p_CODIOFICDEST in MOVIMIENTO.CODIOFICDEST%type
) is
begin
insert into MOVIMIENTO(
OBSEUBIC
,TIPOMOVI
,ESTAMOVI
,FECHMOVI
,CODIEQUI
,CODIMOVI
,CODIEMPL
,CODIOFICORIG
,CODIOFICDEST
) values (
p_OBSEUBIC
,p_TIPOMOVI
,p_ESTAMOVI
,p_FECHMOVI
,p_CODIEQUI
,p_CODIMOVI
,p_CODIEMPL
,p_CODIOFICORIG
,p_CODIOFICDEST
);end;
-- update
procedure upd (
p_OBSEUBIC in MOVIMIENTO.OBSEUBIC%type default null 
,p_TIPOMOVI in MOVIMIENTO.TIPOMOVI%type
,p_ESTAMOVI in MOVIMIENTO.ESTAMOVI%type
,p_FECHMOVI in MOVIMIENTO.FECHMOVI%type
,p_CODIEQUI in MOVIMIENTO.CODIEQUI%type
,p_CODIMOVI in MOVIMIENTO.CODIMOVI%type
,p_CODIEMPL in MOVIMIENTO.CODIEMPL%type
,p_CODIOFICORIG in MOVIMIENTO.CODIOFICORIG%type
,p_CODIOFICDEST in MOVIMIENTO.CODIOFICDEST%type
) is
begin
update MOVIMIENTO set
OBSEUBIC = p_OBSEUBIC
,TIPOMOVI = p_TIPOMOVI
,ESTAMOVI = p_ESTAMOVI
,FECHMOVI = p_FECHMOVI
where CODIMOVI = p_CODIMOVI and CODIEQUI = p_CODIEQUI and CODIEMPL = p_CODIEMPL and CODIOFICORIG = p_CODIOFICORIG and CODIOFICDEST = p_CODIOFICDEST;
end;
-- del
procedure del (
p_CODIMOVI in MOVIMIENTO.CODIMOVI%type
,p_CODIEQUI in MOVIMIENTO.CODIEQUI%type
,p_CODIEMPL in MOVIMIENTO.CODIEMPL%type
,p_CODIOFICORIG in MOVIMIENTO.CODIOFICORIG%type
,p_CODIOFICDEST in MOVIMIENTO.CODIOFICDEST%type
) is
begin
delete from MOVIMIENTO
where CODIMOVI = p_CODIMOVI and CODIEQUI = p_CODIEQUI and CODIEMPL = p_CODIEMPL and CODIOFICORIG = p_CODIOFICORIG and CODIOFICDEST = p_CODIOFICDEST;
end;
end MOVIMIENTO_tapi;
