CREATE OR REPLACE FUNCTION SCOTT.SF_BUSCA_PACIENTE_HOSPITAL
(PVI_TIPO_HISTORIA SCOTT.hos_cuenta_apertura_cab.COD_TIPO_HISTORIA%TYPE,
PVI_COD_HISTORIA SCOTT.hos_cuenta_apertura_cab.COD_HISTORIA_PACIENTE%TYPE)
RETURN VARCHAR2
IS PVO_TA VARCHAR2(10);
BEGIN

    SELECT F.IND_TIPO_ATENCION
    INTO PVO_TA
    FROM SCOTT.HOS_CUENTA_APERTURA_CAB F
    WHERE F.COD_TIPO_HISTORIA = pvi_tipo_historia
    AND F.COD_HISTORIA_PACIENTE = pvi_cod_historia
    AND F.IND_ESTADO = '1';

RETURN PVO_TA;
END;
/