--------------------------------------------------------
-- Archivo creado  - domingo-septiembre-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence TBCLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VERIFICADB"."TBCLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TBINSPECCION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VERIFICADB"."TBINSPECCION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TBPARAMETRO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VERIFICADB"."TBPARAMETRO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table TBCLIENTE
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBCLIENTE" 
   (	"CODCLIENTE" NUMBER(19,0), 
	"NUTIPODOCUMENTO" NUMBER(10,0) DEFAULT NULL, 
	"NONUMERODOCUMENTO" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NOAPELLIDOPATERNO" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NOAPELLIDOMATERNO" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NONOMBRES" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NOCORREO" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL, 
	"FECREACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"FEMODIFICACION" TIMESTAMP (6) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER, 
	"CODUSRMODIFICACION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBCOMPANIA
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBCOMPANIA" 
   (	"CODCOMPANIA" NUMBER(10,0), 
	"NURUC" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"NORAZONSOCIAL" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FECREACION" DATE DEFAULT NULL, 
	"FEMODIFICACION" DATE DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBDEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBDEPARTAMENTO" 
   (	"CODDEPARTAMENTO" NUMBER(10,0), 
	"NODEPARTAMENTO" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FLESTADO" NUMBER(1,0) DEFAULT 1, 
	"FECREACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"FEMODIFICACION" TIMESTAMP (6) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBDISTRITO
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBDISTRITO" 
   (	"CODDISTRITO" NUMBER(10,0), 
	"NODISTRITO" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CODPROVINCIA" NUMBER(10,0), 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FECREACION" DATE DEFAULT NULL, 
	"FEMODIFICACION" DATE DEFAULT NULL, 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBINSPECCION
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBINSPECCION" 
   (	"CODINSPECCION" NUMBER(19,0), 
	"CODCLIENTE" NUMBER(19,0), 
	"CODDISTRITO" NUMBER(10,0), 
	"NONROSOLICITUD" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NUMOTIVO" NUMBER(10,0), 
	"NUESTADOINSP" NUMBER(10,0), 
	"TXDIRECCION" VARCHAR2(2000 BYTE) DEFAULT NULL, 
	"TXMAPALATITUD" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"FLESTADO" NUMBER(22,0) DEFAULT NULL, 
	"NUVISITA" NUMBER, 
	"CODUSUARIODUENIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBINSPECTORINSPECCION
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBINSPECTORINSPECCION" 
   (	"CODINSPECCION" NUMBER(19,0), 
	"CODUSUARIO" NUMBER(10,0), 
	"FEASIGNACION" DATE DEFAULT current_timestamp, 
	"FEHRINSPECCION" TIMESTAMP (6) DEFAULT current_timestamp, 
	"TXFOTO" VARCHAR2(2000 BYTE) DEFAULT NULL, 
	"TXAUDIO" VARCHAR2(2000 BYTE) DEFAULT NULL, 
	"FLVIVENCIA" VARCHAR2(2000 BYTE) DEFAULT NULL, 
	"FECREACION" TIMESTAMP (6) DEFAULT current_timestamp, 
	"FEMODIFICACION" TIMESTAMP (6) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"NOENTREVISTADO" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NUPARENTESCO" NUMBER(10,0) DEFAULT NULL, 
	"NUTIPODOCENTREVISTADO" NUMBER(10,0) DEFAULT NULL, 
	"NODOCENTREVISTADO" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NUTIPOUBICACION" NUMBER(10,0) DEFAULT NULL, 
	"NUTIPOZONA" NUMBER(10,0) DEFAULT NULL, 
	"NUTIPOVIVIENDA" NUMBER(10,0) DEFAULT NULL, 
	"NUESTADOVIVIENDA" NUMBER(10,0) DEFAULT NULL, 
	"NUTIPOPROPIEDAD" NUMBER(10,0) DEFAULT NULL, 
	"QTHABITANTE" NUMBER(10,0) DEFAULT NULL, 
	"QTCARGAFAMILIAR" NUMBER(10,0) DEFAULT NULL, 
	"QTPISO" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBMENU
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBMENU" 
   (	"CODMENU" NUMBER(10,0), 
	"CODSUPERIOR" NUMBER(10,0) DEFAULT NULL, 
	"NOMENU" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"TXDESCRIPCION" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"TXURL" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"NUORDEN" NUMBER(10,0) DEFAULT NULL, 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FECREACION" DATE DEFAULT NULL, 
	"FEMODIFICACION" DATE DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBMENUPERFIL
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBMENUPERFIL" 
   (	"CODPERFIL" NUMBER(10,0), 
	"CODMENU" NUMBER(10,0), 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FECREACION" DATE DEFAULT NULL, 
	"FEMODIFICACION" DATE DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBPARAMETRO
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBPARAMETRO" 
   (	"CODPARAMETRO" NUMBER(10,0), 
	"CODSUPERIOR" NUMBER(10,0) DEFAULT NULL, 
	"NOPARAMETRO" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"TXDESCRIPCION" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FECREACION" TIMESTAMP (6) DEFAULT current_timestamp, 
	"FEMODIFICACION" TIMESTAMP (6) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBPERFIL
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBPERFIL" 
   (	"CODPERFIL" NUMBER(10,0), 
	"TXDESCRIPCION" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FECREACION" DATE DEFAULT NULL, 
	"FEMODIFICACION" DATE DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBPROVINCIA
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBPROVINCIA" 
   (	"CODPROVINCIA" NUMBER(10,0), 
	"NOPROVINCIA" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CODDEPARTAMENTO" NUMBER(10,0), 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FECREACION" DATE DEFAULT NULL, 
	"FEMODIFICACION" DATE DEFAULT NULL, 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBREPORTEINSPECCION
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBREPORTEINSPECCION" 
   (	"CODINSPECCION" NUMBER(19,0), 
	"CODCOMPANIA" NUMBER(10,0), 
	"NORAZONSOCIAL" VARCHAR2(20 BYTE), 
	"NURUC" VARCHAR2(20 BYTE), 
	"CODCLIENTE" NUMBER(19,0), 
	"NUTIPODOCUMENTO" NUMBER(10,0), 
	"NONUMERODOCUMENTO" VARCHAR2(100 BYTE), 
	"NONOMBRES" VARCHAR2(100 BYTE), 
	"NUMOTIVO" NUMBER(10,0), 
	"NONOMBREMOTIVO" VARCHAR2(100 BYTE), 
	"FLESTADO" NUMBER(22,0), 
	"CODINSPECTOR" NUMBER(10,0), 
	"CODDISTRITO" NUMBER(10,0), 
	"NODISTRITO" VARCHAR2(50 BYTE), 
	"CODPROVINCIA" NUMBER(10,0), 
	"NOPROVINCIA" VARCHAR2(50 BYTE), 
	"CODDEPARTAMENTO" NUMBER(10,0), 
	"NODEPARTAMENTO" VARCHAR2(50 BYTE), 
	"TXDIRECCION" VARCHAR2(2000 BYTE), 
	"NUESTADOINSP" NUMBER(10,0), 
	"NOESTADOINSPECCION" VARCHAR2(100 BYTE), 
	"NUTIPOUBICACION" NUMBER(10,0), 
	"NOENTREVISTADO" VARCHAR2(100 BYTE), 
	"NUTIPODOCENTREVISTADO" NUMBER(10,0), 
	"NODOCENTREVISTADO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBUSUARIO
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBUSUARIO" 
   (	"CODUSUARIO" NUMBER(10,0), 
	"CODUSUARIOSUPERIOR" NUMBER(10,0) DEFAULT NULL, 
	"NUTIPOUSUARIO" NUMBER(10,0) DEFAULT NULL, 
	"NOMUSUARIO" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"TXCLAVE" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"NONOMBRES" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NOAPELLIDOS" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NOCORREO" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FECREACION" DATE DEFAULT NULL, 
	"FEMODIFICACION" DATE DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBUSUARIOCOMPANIAPERFIL
--------------------------------------------------------

  CREATE TABLE "VERIFICADB"."TBUSUARIOCOMPANIAPERFIL" 
   (	"CODUSUARIO" NUMBER(10,0), 
	"CODCOMPANIA" NUMBER(10,0), 
	"CODPERFIL" NUMBER(10,0), 
	"FLESTADO" NUMBER(1,0) DEFAULT NULL, 
	"CODUSRCREACION" NUMBER(10,0) DEFAULT NULL, 
	"CODUSRMODIFICACION" NUMBER(10,0) DEFAULT NULL, 
	"FECREACION" DATE DEFAULT current_timestamp, 
	"FEMODIFICACION" DATE DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure SP_FINALIZARINSPECCIONES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "VERIFICADB"."SP_FINALIZARINSPECCIONES" (
	   PI_NUVISITAS IN TBINSPECCION.NUVISITA%type ,
       PO_CODIGO OUT  VARCHAR,
        PO_MENSAJE OUT  VARCHAR)
as
 cursor c_insepcc is SELECT * FROM TBINSPECCION WHERE NUVISITA > PI_NUVISITAS;
BEGIN 
  for registro in c_insepcc loop
    UPDATE TBINSPECCION
    SET TBINSPECCION.NUESTADOINSP = 20
    WHERE TBINSPECCION.CODINSPECCION = registro.CODINSPECCION AND TBINSPECCION.NUESTADOINSP < 20;

end loop;

 	 PO_CODIGO := '0';
	 PO_MENSAJE := 'Consulta exitosa';
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTARINSPECCIONDETALLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "VERIFICADB"."SP_INSERTARINSPECCIONDETALLE" ( 
PI_CODINSPECCION IN TBINSPECCION.CODINSPECCION%type, 
PI_CODUSUARIO IN TBINSPECCION.CODUSUARIODUENIO%type,
PI_FEASIGNACION IN TBINSPECTORINSPECCION.FEASIGNACION%type,
PI_FEHRINSPECCION IN TBINSPECTORINSPECCION.FEHRINSPECCION%type,
PI_FLVIVENCIA IN TBINSPECTORINSPECCION.FLVIVENCIA%type,
PI_CODUSRCREACION IN TBINSPECTORINSPECCION.CODUSRCREACION%type,
PI_NOENTREVISTADO IN TBINSPECTORINSPECCION.NOENTREVISTADO%type,
PI_NUPARENTESCO IN TBINSPECTORINSPECCION.NUPARENTESCO%type,
PI_NUTIPODOCENTREVISTADO IN TBINSPECTORINSPECCION.NUTIPODOCENTREVISTADO%type,
PI_NODOCENTREVISTADO IN TBINSPECTORINSPECCION.NODOCENTREVISTADO%type,
PI_NUTIPOUBICACION IN TBINSPECTORINSPECCION.NUTIPOUBICACION%type,
PI_NUTIPOZONA IN TBINSPECTORINSPECCION.NUTIPOZONA%type,
PI_NUTIPOVIVIENDA IN TBINSPECTORINSPECCION.NUTIPOVIVIENDA%type,
PI_NUESTADOVIVIENDA IN TBINSPECTORINSPECCION.NUESTADOVIVIENDA%type,
PI_NUTIPOPROPIEDAD IN TBINSPECTORINSPECCION.NUTIPOPROPIEDAD%type,
PI_QTHABITANTE IN TBINSPECTORINSPECCION.QTHABITANTE%type,
PI_QTCARGAFAMILIAR IN TBINSPECTORINSPECCION.QTCARGAFAMILIAR%type,
PI_QTPISO IN TBINSPECTORINSPECCION.QTPISO%type )
as
  v_msg varchar2(1000);
  v_nuvisita TBINSPECCION.NUVISITA%type;
  v_NUESTADOINSP TBINSPECCION.NUESTADOINSP%type;

  v_excep1 Exception;
begin

select 	NUVISITA, NUESTADOINSP 
	into v_nuvisita, v_NUESTADOINSP
	from VERIFICADB.TBINSPECCION
	where CODINSPECCION = PI_CODINSPECCION
	for update;

  -- Verificación
	if v_NUESTADOINSP = 20 then
        raise v_excep1;
	end if;

     	v_nuvisita := v_nuvisita + 1;
  update VERIFICADB.TBINSPECCION
		set NUVISITA  = v_nuvisita,
		 NUESTADOINSP  = 19
		where CODINSPECCION = PI_CODINSPECCION;
  -- Movimiento de retiro
    Insert into VERIFICADB.TBINSPECTORINSPECCION (CODINSPECCION,
    CODUSUARIO,FEASIGNACION,FEHRINSPECCION,TXFOTO,TXAUDIO,
    FLVIVENCIA,FECREACION,FEMODIFICACION, CODUSRCREACION,
    CODUSRMODIFICACION,NOENTREVISTADO,NUPARENTESCO,
    NUTIPODOCENTREVISTADO,NODOCENTREVISTADO,NUTIPOUBICACION,
    NUTIPOZONA,NUTIPOVIVIENDA,NUESTADOVIVIENDA,NUTIPOPROPIEDAD,
    QTHABITANTE,QTCARGAFAMILIAR,QTPISO) 
    values (PI_CODINSPECCION,PI_CODUSUARIO,PI_FEASIGNACION,
   PI_FEHRINSPECCION,null,null,PI_FLVIVENCIA,current_timestamp,
    null,PI_CODUSRCREACION,null,PI_NOENTREVISTADO,PI_NUPARENTESCO,
    PI_NUTIPODOCENTREVISTADO,PI_NODOCENTREVISTADO,PI_NUTIPOUBICACION,
    PI_NUTIPOZONA,PI_NUTIPOVIVIENDA,PI_NUESTADOVIVIENDA,PI_NUTIPOPROPIEDAD,
    PI_QTHABITANTE,PI_QTCARGAFAMILIAR,PI_QTPISO);

commit;
exception
  when v_excep1 then
    rollback; -- cancelar transacciÃ³n
    raise_application_error(-20001,'Inspección ya fue finalizada.');
  when others then
    v_msg := sqlerrm; -- capturar mensaje de error
    rollback; -- cancelar transacciÃ³n
    raise_application_error(-20001,v_msg);
end;

/
--------------------------------------------------------
--  DDL for Procedure SP_OBTENERINSPECCION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "VERIFICADB"."SP_OBTENERINSPECCION" (
PI_CODINSPECCION IN  TBINSPECCION.CODINSPECCION%type ,
PI_CODCOMPANIA IN  TBCOMPANIA.CODCOMPANIA %type ,
PI_CODCLIENTE IN  TBINSPECCION.CODCLIENTE%type ,
PI_NUTIPODOCUMENTO IN  TBCLIENTE.NUTIPODOCUMENTO%type ,
PI_NONUMERODOCUMENTO IN  TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NONOMBRES IN  TBCLIENTE.NONOMBRES%type,
PI_NOAPELLIDOPATERNO IN  TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NONOMBRECOMPLETO IN  VARCHAR,
PI_NUMOTIVO IN  TBINSPECCION.NUMOTIVO%type ,
PI_NOMOTIVO IN  TBPARAMETRO.NOPARAMETRO%type,
PI_NUESTADOINSP IN  TBPARAMETRO.NOPARAMETRO%type ,
PI_CODDISTRITO IN  TBDISTRITO.CODDISTRITO%type ,
PI_FLESTADO IN  TBINSPECCION.FLESTADO%type,
PO_TOTAL OUT  INT,
PO_CODIGO OUT  VARCHAR,
PO_MENSAJE OUT  VARCHAR
) AS


BEGIN

  delete from VERIFICADB.TBREPORTEINSPECCION;

--total registros
SELECT COUNT(TBINSPECCION.CODINSPECCION) INTO PO_TOTAL FROM         TBCLIENTE  
	 inner JOIN TBINSPECCION on TBINSPECCION.CODCLIENTE = TBCLIENTE.CODCLIENTE
	INNER JOIN TBUSUARIO  ON TBINSPECCION.CODUSUARIOduenio = TBUSUARIO.CODUSUARIO
	INNER JOIN TBUSUARIOCOMPANIAPERFIL  ON TBUSUARIO.CODUSUARIO = TBUSUARIOCOMPANIAPERFIL.CODUSUARIO
	INNER JOIN TBCOMPANIA  ON TBUSUARIOCOMPANIAPERFIL.CODCOMPANIA = TBCOMPANIA.CODCOMPANIA
	INNER JOIN TBPARAMETRO  ON TBINSPECCION.NUMOTIVO = TBPARAMETRO.CODPARAMETRO
	INNER JOIN TBDISTRITO  ON TBINSPECCION.CODDISTRITO = TBDISTRITO.CODDISTRITO
	INNER JOIN TBPROVINCIA  ON TBDISTRITO.CODPROVINCIA = TBPROVINCIA.CODPROVINCIA
	INNER JOIN TBDEPARTAMENTO  ON TBPROVINCIA.CODDEPARTAMENTO = TBDEPARTAMENTO.CODDEPARTAMENTO
	INNER JOIN TBPARAMETRO  ON TBINSPECCION.NUESTADOINSP = TBPARAMETRO.CODPARAMETRO
	LEFT JOIN TBINSPECTORINSPECCION  ON TBINSPECCION.CODINSPECCION = TBINSPECTORINSPECCION.CODINSPECCION
	WHERE (TBINSPECCION.CODINSPECCION = PI_CODINSPECCION OR PI_CODINSPECCION IS NULL OR PI_CODINSPECCION = 0)
	AND (TBUSUARIOCOMPANIAPERFIL.CODCOMPANIA = PI_CODCOMPANIA OR PI_CODCOMPANIA IS NULL OR PI_CODCOMPANIA = 0)
	AND (TBINSPECCION.CODCLIENTE = PI_CODCLIENTE OR PI_CODCLIENTE IS NULL OR PI_CODCLIENTE = 0)
	AND (TBCLIENTE.NUTIPODOCUMENTO = PI_NUTIPODOCUMENTO OR PI_NUTIPODOCUMENTO IS NULL OR PI_NUTIPODOCUMENTO = 0)
	AND (TBCLIENTE.NONUMERODOCUMENTO = PI_NONUMERODOCUMENTO  OR PI_NONUMERODOCUMENTO  IS NULL OR PI_NONUMERODOCUMENTO = '')
	AND (TBCLIENTE.NONOMBRES = PI_NONOMBRES OR PI_NONOMBRES IS NULL OR PI_NONOMBRES = '')
	AND (TBCLIENTE.NOAPELLIDOPATERNO = PI_NOAPELLIDOPATERNO OR PI_NOAPELLIDOPATERNO IS NULL OR PI_NOAPELLIDOPATERNO = '')
	AND (TBINSPECCION.NUMOTIVO = PI_NUMOTIVO OR PI_NUMOTIVO IS NULL OR PI_NUMOTIVO = 0) 
	AND (TBPARAMETRO.NOPARAMETRO = PI_NOMOTIVO OR PI_NOMOTIVO IS NULL OR PI_NOMOTIVO = '')
	AND (TBINSPECCION.NUESTADOINSP = PI_NUESTADOINSP OR PI_NUESTADOINSP IS NULL OR PI_NUESTADOINSP = 0)
	AND (TBINSPECCION.CODDISTRITO = PI_CODDISTRITO OR PI_CODDISTRITO IS NULL OR PI_CODDISTRITO = 0)
	AND (TBINSPECCION.FLESTADO = PI_FLESTADO OR PI_FLESTADO IS NULL OR PI_FLESTADO = 0);
--SELECT PO_TOTAL;
IF PO_TOTAL > 0 THEN

INSERT INTO TBREPORTEINSPECCION (    
	SELECT TBINSPECCION.CODINSPECCION as CODINSPECCION,
		TBCOMPANIA.CODCOMPANIA as CODCOMPANIA,
		TBCOMPANIA.NORAZONSOCIAL as NORAZONSOCIAL,
		TBCOMPANIA.NURUC as NURUC ,
		TBINSPECCION.CODCLIENTE as CODCLIENTE,
		TBCLIENTE.NUTIPODOCUMENTO as NUTIPODOCUMENTO, 
		TBCLIENTE.NONUMERODOCUMENTO as NONUMERODOCUMENTO,
		TBCLIENTE.NONOMBRES as NONOMBRES,
		TBINSPECCION.NUMOTIVO as NUMOTIVO,
		TBPARAMETRO.NOPARAMETRO AS NONOMBREMOTIVO ,
		TBINSPECCION.FLESTADO as FLESTADO,
		TBINSPECTORINSPECCION.CODUSUARIO AS CODINSPECTOR,
		TBINSPECCION.CODDISTRITO as CODDISTRITO,
		TBDISTRITO.NODISTRITO as NODISTRITO,
		TBDISTRITO.CODPROVINCIA as CODPROVINCIA ,
		TBPROVINCIA.NOPROVINCIA as NOPROVINCIA,
		TBPROVINCIA.CODDEPARTAMENTO as CODDEPARTAMENTO ,
		TBDEPARTAMENTO.NODEPARTAMENTO as NODEPARTAMENTO, 
		TBINSPECCION.TXDIRECCION as TXDIRECCION ,
    	TBINSPECCION.NUESTADOINSP as NUESTADOINSP ,
		TBPARAMETRO.NOPARAMETRO AS NOESTADOINSPECCION,
		TBINSPECTORINSPECCION.NUTIPOUBICACION as NUTIPOUBICACION,
		TBINSPECTORINSPECCION.NOENTREVISTADO as NOENTREVISTADO, 
		TBINSPECTORINSPECCION.NUTIPODOCENTREVISTADO as NUTIPODOCENTREVISTADO, 
		TBINSPECTORINSPECCION.NODOCENTREVISTADO as NODOCENTREVISTADO
        from 
           TBCLIENTE  
	 inner JOIN TBINSPECCION on TBINSPECCION.CODCLIENTE = TBCLIENTE.CODCLIENTE
	INNER JOIN TBUSUARIO  ON TBINSPECCION.CODUSUARIOduenio = TBUSUARIO.CODUSUARIO
	INNER JOIN TBUSUARIOCOMPANIAPERFIL  ON TBUSUARIO.CODUSUARIO = TBUSUARIOCOMPANIAPERFIL.CODUSUARIO
	INNER JOIN TBCOMPANIA  ON TBUSUARIOCOMPANIAPERFIL.CODCOMPANIA = TBCOMPANIA.CODCOMPANIA
	INNER JOIN TBPARAMETRO  ON TBINSPECCION.NUMOTIVO = TBPARAMETRO.CODPARAMETRO
	INNER JOIN TBDISTRITO  ON TBINSPECCION.CODDISTRITO = TBDISTRITO.CODDISTRITO
	INNER JOIN TBPROVINCIA  ON TBDISTRITO.CODPROVINCIA = TBPROVINCIA.CODPROVINCIA
	INNER JOIN TBDEPARTAMENTO  ON TBPROVINCIA.CODDEPARTAMENTO = TBDEPARTAMENTO.CODDEPARTAMENTO
	INNER JOIN TBPARAMETRO  ON TBINSPECCION.NUESTADOINSP = TBPARAMETRO.CODPARAMETRO
	LEFT JOIN TBINSPECTORINSPECCION  ON TBINSPECCION.CODINSPECCION = TBINSPECTORINSPECCION.CODINSPECCION
	WHERE (TBINSPECCION.CODINSPECCION = PI_CODINSPECCION OR PI_CODINSPECCION IS NULL OR PI_CODINSPECCION = 0)
	AND (TBUSUARIOCOMPANIAPERFIL.CODCOMPANIA = PI_CODCOMPANIA OR PI_CODCOMPANIA IS NULL OR PI_CODCOMPANIA = 0)
	AND (TBINSPECCION.CODCLIENTE = PI_CODCLIENTE OR PI_CODCLIENTE IS NULL OR PI_CODCLIENTE = 0)
	AND (TBCLIENTE.NUTIPODOCUMENTO = PI_NUTIPODOCUMENTO OR PI_NUTIPODOCUMENTO IS NULL OR PI_NUTIPODOCUMENTO = 0)
	AND (TBCLIENTE.NONUMERODOCUMENTO = PI_NONUMERODOCUMENTO  OR PI_NONUMERODOCUMENTO  IS NULL OR PI_NONUMERODOCUMENTO = '')
	AND (TBCLIENTE.NONOMBRES = PI_NONOMBRES OR PI_NONOMBRES IS NULL OR PI_NONOMBRES = '')
	AND (TBCLIENTE.NOAPELLIDOPATERNO = PI_NOAPELLIDOPATERNO OR PI_NOAPELLIDOPATERNO IS NULL OR PI_NOAPELLIDOPATERNO = '')
	AND (TBINSPECCION.NUMOTIVO = PI_NUMOTIVO OR PI_NUMOTIVO IS NULL OR PI_NUMOTIVO = 0) 
	AND (TBPARAMETRO.NOPARAMETRO = PI_NOMOTIVO OR PI_NOMOTIVO IS NULL OR PI_NOMOTIVO = '')
	AND (TBINSPECCION.NUESTADOINSP = PI_NUESTADOINSP OR PI_NUESTADOINSP IS NULL OR PI_NUESTADOINSP = 0)
	AND (TBINSPECCION.CODDISTRITO = PI_CODDISTRITO OR PI_CODDISTRITO IS NULL OR PI_CODDISTRITO = 0)
	AND (TBINSPECCION.FLESTADO = PI_FLESTADO OR PI_FLESTADO IS NULL OR PI_FLESTADO = 0)
    );

	 PO_CODIGO := '0';
	 PO_MENSAJE := 'Consulta exitosa';
ELSE 
	 PO_CODIGO := '1';
	 PO_MENSAJE := 'No existen datos';
END IF;
END ;

/
--------------------------------------------------------
--  DDL for Package PKG_CLIENTE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "VERIFICADB"."PKG_CLIENTE" as 
 
  PROCEDURE insertar(
PI_NUTIPODOCUMENTO IN TBCLIENTE.NUTIPODOCUMENTO%type,
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NOAPELLIDOPATERNO IN TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NOAPELLIDOMATERNO IN TBCLIENTE.NOAPELLIDOMATERNO%type,
PI_NONOMBRES IN TBCLIENTE.NONOMBRES%type,
PI_NOCORREO IN TBCLIENTE.NOCORREO%type,
PI_FLESTADO IN TBCLIENTE.FLESTADO%type,
PI_CODUSRCREACION IN TBCLIENTE.CODUSRCREACION%type,
PO_CODCLIENTE OUT TBCLIENTE.CODCLIENTE%type ); 

PROCEDURE obtener( 
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PO_CODCLIENTE OUT TBCLIENTE.CODCLIENTE%type,
PO_NUTIPODOCUMENTO OUT TBCLIENTE.NUTIPODOCUMENTO%type,
PO_NONUMERODOCUMENTO OUT TBCLIENTE.NONUMERODOCUMENTO%type,
PO_NOAPELLIDOPATERNO OUT TBCLIENTE.NOAPELLIDOPATERNO%type,
PO_NOAPELLIDOMATERNO OUT TBCLIENTE.NOAPELLIDOMATERNO%type,
PO_NONOMBRES OUT TBCLIENTE.NONOMBRES%type,
PO_NOCORREO OUT TBCLIENTE.NOCORREO%type,
PO_FLESTADO OUT TBCLIENTE.FLESTADO%type,
PO_FECREACION OUT TBCLIENTE.FECREACION%type,
PO_FEMODIFICACION OUT TBCLIENTE.FEMODIFICACION%type ,
PO_CODUSRCREACION OUT TBCLIENTE.CODUSRCREACION%type,
PO_CODUSRMODIFICACION OUT TBCLIENTE.CODUSRMODIFICACION%TYPE  ); 

PROCEDURE actualizar( 
PI_CODCLIENTE IN TBCLIENTE.CODCLIENTE%type,
PI_NUTIPODOCUMENTO IN TBCLIENTE.NUTIPODOCUMENTO%type,
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NOAPELLIDOPATERNO IN TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NOAPELLIDOMATERNO IN TBCLIENTE.NOAPELLIDOMATERNO%type,
PI_NONOMBRES IN TBCLIENTE.NONOMBRES%type,
PI_NOCORREO IN TBCLIENTE.NOCORREO%type,
PI_FLESTADO IN TBCLIENTE.FLESTADO%type,
PI_CODUSRMODIFICACION IN TBCLIENTE.CODUSRMODIFICACION%type,
PO_RESPUESTA OUT VARCHAR2 ) ; 

PROCEDURE eliminar (
PI_CODCLIENTE IN TBCLIENTE.CODCLIENTE%type,
PO_RESPUESTA OUT VARCHAR2
 ) ; 


END pkg_cliente;

/
--------------------------------------------------------
--  DDL for Package Body PKG_CLIENTE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "VERIFICADB"."PKG_CLIENTE" as 

PROCEDURE insertar( 
PI_NUTIPODOCUMENTO IN TBCLIENTE.NUTIPODOCUMENTO%type,
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NOAPELLIDOPATERNO IN TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NOAPELLIDOMATERNO IN TBCLIENTE.NOAPELLIDOMATERNO%type,
PI_NONOMBRES IN TBCLIENTE.NONOMBRES%type,
PI_NOCORREO IN TBCLIENTE.NOCORREO%type,
PI_FLESTADO IN TBCLIENTE.FLESTADO%type,
PI_CODUSRCREACION IN TBCLIENTE.CODUSRCREACION%type,
PO_CODCLIENTE OUT TBCLIENTE.CODCLIENTE%type )
IS
BEGIN
insert into TBCLIENTE(CODCLIENTE,
NUTIPODOCUMENTO,
NONUMERODOCUMENTO, 
NOAPELLIDOPATERNO,
NOAPELLIDOMATERNO ,
NONOMBRES,
NOCORREO,
FLESTADO,
CODUSRCREACION
) values(tbcliente_seq.nextval,
PI_NUTIPODOCUMENTO,
PI_NONUMERODOCUMENTO, 
PI_NOAPELLIDOPATERNO,
PI_NOAPELLIDOMATERNO ,
PI_NONOMBRES,
PI_NOCORREO,
PI_FLESTADO,
PI_CODUSRCREACION)
	RETURNING CODCLIENTE INTO PO_CODCLIENTE;
	commit;

END; 

PROCEDURE obtener( 
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PO_CODCLIENTE OUT TBCLIENTE.CODCLIENTE%type,
PO_NUTIPODOCUMENTO OUT TBCLIENTE.NUTIPODOCUMENTO%type,
PO_NONUMERODOCUMENTO OUT TBCLIENTE.NONUMERODOCUMENTO%type,
PO_NOAPELLIDOPATERNO OUT TBCLIENTE.NOAPELLIDOPATERNO%type,
PO_NOAPELLIDOMATERNO OUT TBCLIENTE.NOAPELLIDOMATERNO%type,
PO_NONOMBRES OUT TBCLIENTE.NONOMBRES%type,
PO_NOCORREO OUT TBCLIENTE.NOCORREO%type,
PO_FLESTADO OUT TBCLIENTE.FLESTADO%type,
PO_FECREACION OUT TBCLIENTE.FECREACION%type,
PO_FEMODIFICACION OUT TBCLIENTE.FEMODIFICACION%type ,
PO_CODUSRCREACION OUT TBCLIENTE.CODUSRCREACION%type,
PO_CODUSRMODIFICACION OUT TBCLIENTE.CODUSRMODIFICACION%type)

IS
BEGIN
 SELECT CODCLIENTE, NUTIPODOCUMENTO,
NONUMERODOCUMENTO,  NOAPELLIDOPATERNO,
NOAPELLIDOMATERNO , NONOMBRES,
NOCORREO, FLESTADO, FECREACION, FEMODIFICACION, CODUSRCREACION,
CODUSRMODIFICACION
  INTO PO_CODCLIENTE, PO_NUTIPODOCUMENTO,
PO_NONUMERODOCUMENTO, PO_NOAPELLIDOPATERNO,
PO_NOAPELLIDOMATERNO , PO_NONOMBRES,
PO_NOCORREO, PO_FLESTADO,
PO_FECREACION, PO_FEMODIFICACION, PO_CODUSRCREACION,
PO_CODUSRMODIFICACION
  from  TBCLIENTE WHERE NONUMERODOCUMENTO = PI_NONUMERODOCUMENTO;

END
 ; 

PROCEDURE actualizar( 
PI_CODCLIENTE IN TBCLIENTE.CODCLIENTE%type,
PI_NUTIPODOCUMENTO IN TBCLIENTE.NUTIPODOCUMENTO%type,
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NOAPELLIDOPATERNO IN TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NOAPELLIDOMATERNO IN TBCLIENTE.NOAPELLIDOMATERNO%type,
PI_NONOMBRES IN TBCLIENTE.NONOMBRES%type,
PI_NOCORREO IN TBCLIENTE.NOCORREO%type,
PI_FLESTADO IN TBCLIENTE.FLESTADO%type,
PI_CODUSRMODIFICACION IN TBCLIENTE.CODUSRMODIFICACION%type,
PO_RESPUESTA OUT VARCHAR2 )
IS
BEGIN

case 
 when (PI_NUTIPODOCUMENTO IS NOT null) then update TBCLIENTE set NUTIPODOCUMENTO = PI_NUTIPODOCUMENTO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NONUMERODOCUMENTO IS NOT  null) then update TBCLIENTE set NONUMERODOCUMENTO = PI_NONUMERODOCUMENTO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NOAPELLIDOPATERNO IS NOT  null) then update TBCLIENTE set NOAPELLIDOPATERNO = PI_NOAPELLIDOPATERNO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NOAPELLIDOMATERNO IS NOT  null) then update TBCLIENTE set  NOAPELLIDOMATERNO  = PI_NOAPELLIDOMATERNO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NONOMBRES IS NOT  null) then update TBCLIENTE set  NONOMBRES = PI_NONOMBRES WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NOCORREO IS NOT  null) then update TBCLIENTE set NOCORREO = PI_NOCORREO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_FLESTADO IS NOT  null) then update TBCLIENTE set FLESTADO = PI_FLESTADO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_CODUSRMODIFICACION IS NOT  null) then update TBCLIENTE set CODUSRMODIFICACION = PI_CODUSRMODIFICACION WHERE CODCLIENTE = PI_CODCLIENTE;
end case;		

update TBCLIENTE set FECREACION = current_timestamp WHERE CODCLIENTE = PI_CODCLIENTE;

		commit;

PO_RESPUESTA := 'OK';


END 
 ; 

PROCEDURE eliminar (
PI_CODCLIENTE IN TBCLIENTE.CODCLIENTE%type,
PO_RESPUESTA OUT VARCHAR2
 )
IS
BEGIN
DELETE FROM TBCLIENTE WHERE CODCLIENTE = PI_CODCLIENTE;
PO_RESPUESTA := 'OK';
END ; 


END pkg_cliente;

/
--------------------------------------------------------
--  Constraints for Table TBUSUARIOCOMPANIAPERFIL
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBUSUARIOCOMPANIAPERFIL" MODIFY ("CODUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBUSUARIOCOMPANIAPERFIL" MODIFY ("CODCOMPANIA" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBUSUARIOCOMPANIAPERFIL" MODIFY ("CODPERFIL" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBUSUARIOCOMPANIAPERFIL" ADD PRIMARY KEY ("CODUSUARIO", "CODCOMPANIA", "CODPERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBCLIENTE
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBCLIENTE" MODIFY ("CODCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBCLIENTE" ADD PRIMARY KEY ("CODCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBDISTRITO
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBDISTRITO" MODIFY ("CODDISTRITO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBDISTRITO" MODIFY ("CODPROVINCIA" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBDISTRITO" ADD PRIMARY KEY ("CODDISTRITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBREPORTEINSPECCION
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBREPORTEINSPECCION" MODIFY ("CODINSPECCION" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBREPORTEINSPECCION" MODIFY ("CODCOMPANIA" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBREPORTEINSPECCION" MODIFY ("CODCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBREPORTEINSPECCION" MODIFY ("NUMOTIVO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBREPORTEINSPECCION" MODIFY ("CODDISTRITO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBREPORTEINSPECCION" MODIFY ("CODPROVINCIA" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBREPORTEINSPECCION" MODIFY ("CODDEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBREPORTEINSPECCION" MODIFY ("NUESTADOINSP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBPARAMETRO
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBPARAMETRO" MODIFY ("CODPARAMETRO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBPARAMETRO" MODIFY ("FECREACION" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBPARAMETRO" ADD PRIMARY KEY ("CODPARAMETRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBINSPECCION
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBINSPECCION" MODIFY ("CODINSPECCION" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBINSPECCION" MODIFY ("CODCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBINSPECCION" MODIFY ("CODDISTRITO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBINSPECCION" MODIFY ("NUMOTIVO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBINSPECCION" MODIFY ("NUESTADOINSP" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBINSPECCION" ADD PRIMARY KEY ("CODINSPECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBCOMPANIA
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBCOMPANIA" MODIFY ("CODCOMPANIA" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBCOMPANIA" ADD PRIMARY KEY ("CODCOMPANIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBMENU
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBMENU" MODIFY ("CODMENU" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBMENU" ADD PRIMARY KEY ("CODMENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBPERFIL
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBPERFIL" MODIFY ("CODPERFIL" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBPERFIL" ADD PRIMARY KEY ("CODPERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBINSPECTORINSPECCION
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBINSPECTORINSPECCION" MODIFY ("CODINSPECCION" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBINSPECTORINSPECCION" MODIFY ("CODUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBINSPECTORINSPECCION" MODIFY ("FEASIGNACION" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBINSPECTORINSPECCION" MODIFY ("FECREACION" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBINSPECTORINSPECCION" ADD PRIMARY KEY ("CODINSPECCION", "CODUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBUSUARIO
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBUSUARIO" MODIFY ("CODUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBUSUARIO" ADD PRIMARY KEY ("CODUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBMENUPERFIL
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBMENUPERFIL" MODIFY ("CODPERFIL" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBMENUPERFIL" MODIFY ("CODMENU" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBMENUPERFIL" ADD PRIMARY KEY ("CODPERFIL", "CODMENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBPROVINCIA
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBPROVINCIA" MODIFY ("CODPROVINCIA" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBPROVINCIA" MODIFY ("CODDEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBPROVINCIA" ADD PRIMARY KEY ("CODPROVINCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBDEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBDEPARTAMENTO" MODIFY ("CODDEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "VERIFICADB"."TBDEPARTAMENTO" ADD PRIMARY KEY ("CODDEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBCLIENTE
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBCLIENTE" ADD CONSTRAINT "TBCLIENTE_TBUSUARIO_FK" FOREIGN KEY ("CODUSRCREACION")
	  REFERENCES "VERIFICADB"."TBUSUARIO" ("CODUSUARIO") ENABLE;
  ALTER TABLE "VERIFICADB"."TBCLIENTE" ADD CONSTRAINT "TBCLIENTE_TBUSUARIO_FK_1" FOREIGN KEY ("CODUSRMODIFICACION")
	  REFERENCES "VERIFICADB"."TBUSUARIO" ("CODUSUARIO") ENABLE;
  ALTER TABLE "VERIFICADB"."TBCLIENTE" ADD CONSTRAINT "TBCLIENTE_PARAMETRO" FOREIGN KEY ("NUTIPODOCUMENTO")
	  REFERENCES "VERIFICADB"."TBPARAMETRO" ("CODPARAMETRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBDISTRITO
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBDISTRITO" ADD CONSTRAINT "TBDISTRITO_PROVINCIA" FOREIGN KEY ("CODPROVINCIA")
	  REFERENCES "VERIFICADB"."TBPROVINCIA" ("CODPROVINCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBINSPECCION
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBINSPECCION" ADD CONSTRAINT "TBINSPECCION_TBCLIENTE_FK" FOREIGN KEY ("CODCLIENTE")
	  REFERENCES "VERIFICADB"."TBCLIENTE" ("CODCLIENTE") ENABLE;
  ALTER TABLE "VERIFICADB"."TBINSPECCION" ADD CONSTRAINT "TBINSPECCION_TBDISTRITO_FK" FOREIGN KEY ("CODDISTRITO")
	  REFERENCES "VERIFICADB"."TBDISTRITO" ("CODDISTRITO") ENABLE;
  ALTER TABLE "VERIFICADB"."TBINSPECCION" ADD CONSTRAINT "TBINSPECCION_PARAMETRO" FOREIGN KEY ("NUMOTIVO")
	  REFERENCES "VERIFICADB"."TBPARAMETRO" ("CODPARAMETRO") ENABLE;
  ALTER TABLE "VERIFICADB"."TBINSPECCION" ADD CONSTRAINT "TBINSPECCION_USUARIODUENIO" FOREIGN KEY ("CODUSUARIODUENIO")
	  REFERENCES "VERIFICADB"."TBUSUARIO" ("CODUSUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBINSPECTORINSPECCION
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBINSPECTORINSPECCION" ADD CONSTRAINT "TBINSPECTORINSPECCION_TBINSPECCION_FK" FOREIGN KEY ("CODINSPECCION")
	  REFERENCES "VERIFICADB"."TBINSPECCION" ("CODINSPECCION") ENABLE;
  ALTER TABLE "VERIFICADB"."TBINSPECTORINSPECCION" ADD CONSTRAINT "TBINSPECTORINSPECCION_TBUSUARIO_FK" FOREIGN KEY ("CODUSUARIO")
	  REFERENCES "VERIFICADB"."TBUSUARIO" ("CODUSUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBMENU
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBMENU" ADD CONSTRAINT "TBMENU_TBMENU_FK" FOREIGN KEY ("CODSUPERIOR")
	  REFERENCES "VERIFICADB"."TBMENU" ("CODMENU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBMENUPERFIL
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBMENUPERFIL" ADD CONSTRAINT "TBMENUPERFIL_TBMENU_FK" FOREIGN KEY ("CODMENU")
	  REFERENCES "VERIFICADB"."TBMENU" ("CODMENU") ENABLE;
  ALTER TABLE "VERIFICADB"."TBMENUPERFIL" ADD CONSTRAINT "TBMENUPERFIL_TBPERFIL_FK" FOREIGN KEY ("CODPERFIL")
	  REFERENCES "VERIFICADB"."TBPERFIL" ("CODPERFIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBPARAMETRO
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBPARAMETRO" ADD CONSTRAINT "TBPARAMETRO_TBPARAMETRO_FK" FOREIGN KEY ("CODSUPERIOR")
	  REFERENCES "VERIFICADB"."TBPARAMETRO" ("CODPARAMETRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBPROVINCIA
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBPROVINCIA" ADD CONSTRAINT "TBPROVINCIA_DEPARTAMENTO" FOREIGN KEY ("CODDEPARTAMENTO")
	  REFERENCES "VERIFICADB"."TBDEPARTAMENTO" ("CODDEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBUSUARIO
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBUSUARIO" ADD CONSTRAINT "TBUSUARIO_TBUSUARIO_FK" FOREIGN KEY ("CODUSUARIOSUPERIOR")
	  REFERENCES "VERIFICADB"."TBUSUARIO" ("CODUSUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBUSUARIOCOMPANIAPERFIL
--------------------------------------------------------

  ALTER TABLE "VERIFICADB"."TBUSUARIOCOMPANIAPERFIL" ADD CONSTRAINT "TBUSUARIOCOMPANIAPERFIL_TBCOMPANIA_FK" FOREIGN KEY ("CODCOMPANIA")
	  REFERENCES "VERIFICADB"."TBCOMPANIA" ("CODCOMPANIA") ENABLE;
  ALTER TABLE "VERIFICADB"."TBUSUARIOCOMPANIAPERFIL" ADD CONSTRAINT "TBUSUARIOCOMPANIAPERFIL_TBPERFIL_FK" FOREIGN KEY ("CODPERFIL")
	  REFERENCES "VERIFICADB"."TBPERFIL" ("CODPERFIL") ENABLE;
  ALTER TABLE "VERIFICADB"."TBUSUARIOCOMPANIAPERFIL" ADD CONSTRAINT "TBUSUARIOCOMPANIAPERFIL_TBUSUARIO_FK" FOREIGN KEY ("CODUSUARIO")
	  REFERENCES "VERIFICADB"."TBUSUARIO" ("CODUSUARIO") ENABLE;
