--------------------------------------------------------
--  DDL for Package PKG_CLIENTE
--------------------------------------------------------

  CREATE OR REPLACE  PACKAGE "VERIFICADB"."PKG_CLIENTE" as 
 
  PROCEDURE insertar(
PI_NUTIPODOCUMENTO IN TBCLIENTE.NUTIPODOCUMENTO%type,
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NOAPELLIDOPATERNO IN TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NOAPELLIDOMATERNO IN TBCLIENTE.NOAPELLIDOMATERNO%type,
PI_NONOMBRES IN TBCLIENTE.NONOMBRES%type,
PI_NOCORREO IN TBCLIENTE.NOCORREO%type,
PI_FLESTADO IN TBCLIENTE.FLESTADO%type,
PI_CODUSRCREACION IN TBCLIENTE.CODUSRCREACION%type,
PO_CODCLIENTE OUT TBCLIENTE.CODCLIENTE%type ); 

PROCEDURE obtener( 
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PO_CODCLIENTE OUT TBCLIENTE.CODCLIENTE%type,
PO_NUTIPODOCUMENTO OUT TBCLIENTE.NUTIPODOCUMENTO%type,
PO_NONUMERODOCUMENTO OUT TBCLIENTE.NONUMERODOCUMENTO%type,
PO_NOAPELLIDOPATERNO OUT TBCLIENTE.NOAPELLIDOPATERNO%type,
PO_NOAPELLIDOMATERNO OUT TBCLIENTE.NOAPELLIDOMATERNO%type,
PO_NONOMBRES OUT TBCLIENTE.NONOMBRES%type,
PO_NOCORREO OUT TBCLIENTE.NOCORREO%type,
PO_FLESTADO OUT TBCLIENTE.FLESTADO%type,
PO_FECREACION OUT TBCLIENTE.FECREACION%type,
PO_FEMODIFICACION OUT TBCLIENTE.FEMODIFICACION%type ,
PO_CODUSRCREACION OUT TBCLIENTE.CODUSRCREACION%type,
PO_CODUSRMODIFICACION OUT TBCLIENTE.CODUSRMODIFICACION%TYPE  ); 

PROCEDURE actualizar( 
PI_CODCLIENTE IN TBCLIENTE.CODCLIENTE%type,
PI_NUTIPODOCUMENTO IN TBCLIENTE.NUTIPODOCUMENTO%type,
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NOAPELLIDOPATERNO IN TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NOAPELLIDOMATERNO IN TBCLIENTE.NOAPELLIDOMATERNO%type,
PI_NONOMBRES IN TBCLIENTE.NONOMBRES%type,
PI_NOCORREO IN TBCLIENTE.NOCORREO%type,
PI_FLESTADO IN TBCLIENTE.FLESTADO%type,
PI_CODUSRMODIFICACION IN TBCLIENTE.CODUSRMODIFICACION%type,
PO_RESPUESTA OUT VARCHAR2 ) ; 

PROCEDURE eliminar (
PI_CODCLIENTE IN TBCLIENTE.CODCLIENTE%type,
PO_RESPUESTA OUT VARCHAR2
 ) ; 


END pkg_cliente;

/
--------------------------------------------------------
--  DDL for Package Body PKG_CLIENTE
--------------------------------------------------------

  CREATE OR REPLACE  PACKAGE BODY "VERIFICADB"."PKG_CLIENTE" as 

PROCEDURE insertar( 
PI_NUTIPODOCUMENTO IN TBCLIENTE.NUTIPODOCUMENTO%type,
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NOAPELLIDOPATERNO IN TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NOAPELLIDOMATERNO IN TBCLIENTE.NOAPELLIDOMATERNO%type,
PI_NONOMBRES IN TBCLIENTE.NONOMBRES%type,
PI_NOCORREO IN TBCLIENTE.NOCORREO%type,
PI_FLESTADO IN TBCLIENTE.FLESTADO%type,
PI_CODUSRCREACION IN TBCLIENTE.CODUSRCREACION%type,
PO_CODCLIENTE OUT TBCLIENTE.CODCLIENTE%type )
IS
BEGIN
insert into TBCLIENTE(CODCLIENTE,
NUTIPODOCUMENTO,
NONUMERODOCUMENTO, 
NOAPELLIDOPATERNO,
NOAPELLIDOMATERNO ,
NONOMBRES,
NOCORREO,
FLESTADO,
CODUSRCREACION
) values(tbcliente_seq.nextval,
PI_NUTIPODOCUMENTO,
PI_NONUMERODOCUMENTO, 
PI_NOAPELLIDOPATERNO,
PI_NOAPELLIDOMATERNO ,
PI_NONOMBRES,
PI_NOCORREO,
PI_FLESTADO,
PI_CODUSRCREACION)
	RETURNING CODCLIENTE INTO PO_CODCLIENTE;
	commit;

END; 

PROCEDURE obtener( 
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PO_CODCLIENTE OUT TBCLIENTE.CODCLIENTE%type,
PO_NUTIPODOCUMENTO OUT TBCLIENTE.NUTIPODOCUMENTO%type,
PO_NONUMERODOCUMENTO OUT TBCLIENTE.NONUMERODOCUMENTO%type,
PO_NOAPELLIDOPATERNO OUT TBCLIENTE.NOAPELLIDOPATERNO%type,
PO_NOAPELLIDOMATERNO OUT TBCLIENTE.NOAPELLIDOMATERNO%type,
PO_NONOMBRES OUT TBCLIENTE.NONOMBRES%type,
PO_NOCORREO OUT TBCLIENTE.NOCORREO%type,
PO_FLESTADO OUT TBCLIENTE.FLESTADO%type,
PO_FECREACION OUT TBCLIENTE.FECREACION%type,
PO_FEMODIFICACION OUT TBCLIENTE.FEMODIFICACION%type ,
PO_CODUSRCREACION OUT TBCLIENTE.CODUSRCREACION%type,
PO_CODUSRMODIFICACION OUT TBCLIENTE.CODUSRMODIFICACION%type)

IS
BEGIN
 SELECT CODCLIENTE, NUTIPODOCUMENTO,
NONUMERODOCUMENTO,  NOAPELLIDOPATERNO,
NOAPELLIDOMATERNO , NONOMBRES,
NOCORREO, FLESTADO, FECREACION, FEMODIFICACION, CODUSRCREACION,
CODUSRMODIFICACION
  INTO PO_CODCLIENTE, PO_NUTIPODOCUMENTO,
PO_NONUMERODOCUMENTO, PO_NOAPELLIDOPATERNO,
PO_NOAPELLIDOMATERNO , PO_NONOMBRES,
PO_NOCORREO, PO_FLESTADO,
PO_FECREACION, PO_FEMODIFICACION, PO_CODUSRCREACION,
PO_CODUSRMODIFICACION
  from  TBCLIENTE WHERE NONUMERODOCUMENTO = PI_NONUMERODOCUMENTO;

END
 ; 

PROCEDURE actualizar( 
PI_CODCLIENTE IN TBCLIENTE.CODCLIENTE%type,
PI_NUTIPODOCUMENTO IN TBCLIENTE.NUTIPODOCUMENTO%type,
PI_NONUMERODOCUMENTO IN TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NOAPELLIDOPATERNO IN TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NOAPELLIDOMATERNO IN TBCLIENTE.NOAPELLIDOMATERNO%type,
PI_NONOMBRES IN TBCLIENTE.NONOMBRES%type,
PI_NOCORREO IN TBCLIENTE.NOCORREO%type,
PI_FLESTADO IN TBCLIENTE.FLESTADO%type,
PI_CODUSRMODIFICACION IN TBCLIENTE.CODUSRMODIFICACION%type,
PO_RESPUESTA OUT VARCHAR2 )
IS
BEGIN

case 
 when (PI_NUTIPODOCUMENTO IS NOT null) then update TBCLIENTE set NUTIPODOCUMENTO = PI_NUTIPODOCUMENTO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NONUMERODOCUMENTO IS NOT  null) then update TBCLIENTE set NONUMERODOCUMENTO = PI_NONUMERODOCUMENTO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NOAPELLIDOPATERNO IS NOT  null) then update TBCLIENTE set NOAPELLIDOPATERNO = PI_NOAPELLIDOPATERNO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NOAPELLIDOMATERNO IS NOT  null) then update TBCLIENTE set  NOAPELLIDOMATERNO  = PI_NOAPELLIDOMATERNO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NONOMBRES IS NOT  null) then update TBCLIENTE set  NONOMBRES = PI_NONOMBRES WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_NOCORREO IS NOT  null) then update TBCLIENTE set NOCORREO = PI_NOCORREO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_FLESTADO IS NOT  null) then update TBCLIENTE set FLESTADO = PI_FLESTADO WHERE CODCLIENTE = PI_CODCLIENTE;
 when (PI_CODUSRMODIFICACION IS NOT  null) then update TBCLIENTE set CODUSRMODIFICACION = PI_CODUSRMODIFICACION WHERE CODCLIENTE = PI_CODCLIENTE;
end case;		

update TBCLIENTE set FECREACION = current_timestamp WHERE CODCLIENTE = PI_CODCLIENTE;

		commit;

PO_RESPUESTA := 'OK';


END 
 ; 

PROCEDURE eliminar (
PI_CODCLIENTE IN TBCLIENTE.CODCLIENTE%type,
PO_RESPUESTA OUT VARCHAR2
 )
IS
BEGIN
DELETE FROM TBCLIENTE WHERE CODCLIENTE = PI_CODCLIENTE;
PO_RESPUESTA := 'OK';
END ; 


END pkg_cliente;

/