create or replace procedure  sp_insertarinspecciondetalle( 
PI_CODINSPECCION IN TBINSPECCION.CODINSPECCION%type, 
PI_CODUSUARIO IN TBINSPECCION.CODUSUARIODUENIO%type,
PI_FEASIGNACION IN TBINSPECTORINSPECCION.FEASIGNACION%type,
PI_FEHRINSPECCION IN TBINSPECTORINSPECCION.FEHRINSPECCION%type,
PI_FLVIVENCIA IN TBINSPECTORINSPECCION.FLVIVENCIA%type,
PI_CODUSRCREACION IN TBINSPECTORINSPECCION.CODUSRCREACION%type,
PI_NOENTREVISTADO IN TBINSPECTORINSPECCION.NOENTREVISTADO%type,
PI_NUPARENTESCO IN TBINSPECTORINSPECCION.NUPARENTESCO%type,
PI_NUTIPODOCENTREVISTADO IN TBINSPECTORINSPECCION.NUTIPODOCENTREVISTADO%type,
PI_NODOCENTREVISTADO IN TBINSPECTORINSPECCION.NODOCENTREVISTADO%type,
PI_NUTIPOUBICACION IN TBINSPECTORINSPECCION.NUTIPOUBICACION%type,
PI_NUTIPOZONA IN TBINSPECTORINSPECCION.NUTIPOZONA%type,
PI_NUTIPOVIVIENDA IN TBINSPECTORINSPECCION.NUTIPOVIVIENDA%type,
PI_NUESTADOVIVIENDA IN TBINSPECTORINSPECCION.NUESTADOVIVIENDA%type,
PI_NUTIPOPROPIEDAD IN TBINSPECTORINSPECCION.NUTIPOPROPIEDAD%type,
PI_QTHABITANTE IN TBINSPECTORINSPECCION.QTHABITANTE%type,
PI_QTCARGAFAMILIAR IN TBINSPECTORINSPECCION.QTCARGAFAMILIAR%type,
PI_QTPISO IN TBINSPECTORINSPECCION.QTPISO%type,
PO_MENSAJE OUT  VARCHAR)
as
  v_msg varchar2(1000);
  v_nuvisita TBINSPECCION.NUVISITA%type;
  v_NUESTADOINSP TBINSPECCION.NUESTADOINSP%type;

  v_excep1 Exception;
begin

select 	NUVISITA, NUESTADOINSP 
	into v_nuvisita, v_NUESTADOINSP
	from VERIFICADB.TBINSPECCION
	where CODINSPECCION = PI_CODINSPECCION
	for update;

  -- Verificación
	if v_NUESTADOINSP = 20 then
        raise v_excep1;
	end if;

     	v_nuvisita := v_nuvisita + 1;
  update VERIFICADB.TBINSPECCION
		set NUVISITA  = v_nuvisita,
		 NUESTADOINSP  = 19
		where CODINSPECCION = PI_CODINSPECCION;
  -- Movimiento de retiro
    Insert into VERIFICADB.TBINSPECTORINSPECCION (CODINSPECCION,
    CODUSUARIO,FEASIGNACION,FEHRINSPECCION,TXFOTO,TXAUDIO,
    FLVIVENCIA,FECREACION,FEMODIFICACION, CODUSRCREACION,
    CODUSRMODIFICACION,NOENTREVISTADO,NUPARENTESCO,
    NUTIPODOCENTREVISTADO,NODOCENTREVISTADO,NUTIPOUBICACION,
    NUTIPOZONA,NUTIPOVIVIENDA,NUESTADOVIVIENDA,NUTIPOPROPIEDAD,
    QTHABITANTE,QTCARGAFAMILIAR,QTPISO) 
    values (PI_CODINSPECCION,PI_CODUSUARIO,PI_FEASIGNACION,
   PI_FEHRINSPECCION,null,null,PI_FLVIVENCIA,current_timestamp,
    null,PI_CODUSRCREACION,null,PI_NOENTREVISTADO,PI_NUPARENTESCO,
    PI_NUTIPODOCENTREVISTADO,PI_NODOCENTREVISTADO,PI_NUTIPOUBICACION,
    PI_NUTIPOZONA,PI_NUTIPOVIVIENDA,PI_NUESTADOVIVIENDA,PI_NUTIPOPROPIEDAD,
    PI_QTHABITANTE,PI_QTCARGAFAMILIAR,PI_QTPISO);

    PO_MENSAJE := 'Se insertó correctamente';

commit;
exception
  when v_excep1 then
    rollback; -- cancelar transacciÃ³n
    --raise_application_error(-20001,'Inspección ya fue finalizada.');
    PO_MENSAJE := 'Inspección ya fue finalizada.';
  when others then
    v_msg := sqlerrm; -- capturar mensaje de error
    rollback; -- cancelar transacciÃ³n
   -- raise_application_error(-20001,v_msg);

    PO_MENSAJE := v_msg;
end;