create or replace  PROCEDURE  SP_obtenerInspeccion(
PI_CODINSPECCION IN  TBINSPECCION.CODINSPECCION%type ,
PI_CODCOMPANIA IN  TBCOMPANIA.CODCOMPANIA %type ,
PI_CODCLIENTE IN  TBINSPECCION.CODCLIENTE%type ,
PI_NUTIPODOCUMENTO IN  TBCLIENTE.NUTIPODOCUMENTO%type ,
PI_NONUMERODOCUMENTO IN  TBCLIENTE.NONUMERODOCUMENTO%type,
PI_NONOMBRES IN  TBCLIENTE.NONOMBRES%type,
PI_NOAPELLIDOPATERNO IN  TBCLIENTE.NOAPELLIDOPATERNO%type,
PI_NONOMBRECOMPLETO IN  VARCHAR,
PI_NUMOTIVO IN  TBINSPECCION.NUMOTIVO%type ,
PI_NOMOTIVO IN  TBPARAMETRO.NOPARAMETRO%type,
PI_NUESTADOINSP IN  TBPARAMETRO.NOPARAMETRO%type ,
PI_CODDISTRITO IN  TBDISTRITO.CODDISTRITO%type ,
PI_FLESTADO IN  TBINSPECCION.FLESTADO%type,
PO_TOTAL OUT  INT,
PO_CODIGO OUT  VARCHAR,
PO_MENSAJE OUT  VARCHAR
) AS


BEGIN

  delete from VERIFICADB.TBREPORTEINSPECCION;

--total registros
SELECT COUNT(TBINSPECCION.CODINSPECCION) INTO PO_TOTAL FROM         TBCLIENTE  
	 inner JOIN TBINSPECCION on TBINSPECCION.CODCLIENTE = TBCLIENTE.CODCLIENTE
	INNER JOIN TBUSUARIO  ON TBINSPECCION.CODUSUARIOduenio = TBUSUARIO.CODUSUARIO
	INNER JOIN TBUSUARIOCOMPANIAPERFIL  ON TBUSUARIO.CODUSUARIO = TBUSUARIOCOMPANIAPERFIL.CODUSUARIO
	INNER JOIN TBCOMPANIA  ON TBUSUARIOCOMPANIAPERFIL.CODCOMPANIA = TBCOMPANIA.CODCOMPANIA
	INNER JOIN TBPARAMETRO  ON TBINSPECCION.NUMOTIVO = TBPARAMETRO.CODPARAMETRO
	INNER JOIN TBDISTRITO  ON TBINSPECCION.CODDISTRITO = TBDISTRITO.CODDISTRITO
	INNER JOIN TBPROVINCIA  ON TBDISTRITO.CODPROVINCIA = TBPROVINCIA.CODPROVINCIA
	INNER JOIN TBDEPARTAMENTO  ON TBPROVINCIA.CODDEPARTAMENTO = TBDEPARTAMENTO.CODDEPARTAMENTO
	INNER JOIN TBPARAMETRO  ON TBINSPECCION.NUESTADOINSP = TBPARAMETRO.CODPARAMETRO
	LEFT JOIN TBINSPECTORINSPECCION  ON TBINSPECCION.CODINSPECCION = TBINSPECTORINSPECCION.CODINSPECCION
	WHERE (TBINSPECCION.CODINSPECCION = PI_CODINSPECCION OR PI_CODINSPECCION IS NULL OR PI_CODINSPECCION = 0)
	AND (TBUSUARIOCOMPANIAPERFIL.CODCOMPANIA = PI_CODCOMPANIA OR PI_CODCOMPANIA IS NULL OR PI_CODCOMPANIA = 0)
	AND (TBINSPECCION.CODCLIENTE = PI_CODCLIENTE OR PI_CODCLIENTE IS NULL OR PI_CODCLIENTE = 0)
	AND (TBCLIENTE.NUTIPODOCUMENTO = PI_NUTIPODOCUMENTO OR PI_NUTIPODOCUMENTO IS NULL OR PI_NUTIPODOCUMENTO = 0)
	AND (TBCLIENTE.NONUMERODOCUMENTO = PI_NONUMERODOCUMENTO  OR PI_NONUMERODOCUMENTO  IS NULL OR PI_NONUMERODOCUMENTO = '')
	AND (TBCLIENTE.NONOMBRES = PI_NONOMBRES OR PI_NONOMBRES IS NULL OR PI_NONOMBRES = '')
	AND (TBCLIENTE.NOAPELLIDOPATERNO = PI_NOAPELLIDOPATERNO OR PI_NOAPELLIDOPATERNO IS NULL OR PI_NOAPELLIDOPATERNO = '')
	AND (TBINSPECCION.NUMOTIVO = PI_NUMOTIVO OR PI_NUMOTIVO IS NULL OR PI_NUMOTIVO = 0) 
	AND (TBPARAMETRO.NOPARAMETRO = PI_NOMOTIVO OR PI_NOMOTIVO IS NULL OR PI_NOMOTIVO = '')
	AND (TBINSPECCION.NUESTADOINSP = PI_NUESTADOINSP OR PI_NUESTADOINSP IS NULL OR PI_NUESTADOINSP = 0)
	AND (TBINSPECCION.CODDISTRITO = PI_CODDISTRITO OR PI_CODDISTRITO IS NULL OR PI_CODDISTRITO = 0)
	AND (TBINSPECCION.FLESTADO = PI_FLESTADO OR PI_FLESTADO IS NULL OR PI_FLESTADO = 0);
--SELECT PO_TOTAL;
IF PO_TOTAL > 0 THEN

INSERT INTO TBREPORTEINSPECCION (    
	SELECT TBINSPECCION.CODINSPECCION as CODINSPECCION,
		TBCOMPANIA.CODCOMPANIA as CODCOMPANIA,
		TBCOMPANIA.NORAZONSOCIAL as NORAZONSOCIAL,
		TBCOMPANIA.NURUC as NURUC ,
		TBINSPECCION.CODCLIENTE as CODCLIENTE,
		TBCLIENTE.NUTIPODOCUMENTO as NUTIPODOCUMENTO, 
		TBCLIENTE.NONUMERODOCUMENTO as NONUMERODOCUMENTO,
		TBCLIENTE.NONOMBRES as NONOMBRES,
		TBINSPECCION.NUMOTIVO as NUMOTIVO,
		TBPARAMETRO.NOPARAMETRO AS NONOMBREMOTIVO ,
		TBINSPECCION.FLESTADO as FLESTADO,
		TBINSPECTORINSPECCION.CODUSUARIO AS CODINSPECTOR,
		TBINSPECCION.CODDISTRITO as CODDISTRITO,
		TBDISTRITO.NODISTRITO as NODISTRITO,
		TBDISTRITO.CODPROVINCIA as CODPROVINCIA ,
		TBPROVINCIA.NOPROVINCIA as NOPROVINCIA,
		TBPROVINCIA.CODDEPARTAMENTO as CODDEPARTAMENTO ,
		TBDEPARTAMENTO.NODEPARTAMENTO as NODEPARTAMENTO, 
		TBINSPECCION.TXDIRECCION as TXDIRECCION ,
    	TBINSPECCION.NUESTADOINSP as NUESTADOINSP ,
		TBPARAMETRO.NOPARAMETRO AS NOESTADOINSPECCION,
		TBINSPECTORINSPECCION.NUTIPOUBICACION as NUTIPOUBICACION,
		TBINSPECTORINSPECCION.NOENTREVISTADO as NOENTREVISTADO, 
		TBINSPECTORINSPECCION.NUTIPODOCENTREVISTADO as NUTIPODOCENTREVISTADO, 
		TBINSPECTORINSPECCION.NODOCENTREVISTADO as NODOCENTREVISTADO
        from 
           TBCLIENTE  
	 inner JOIN TBINSPECCION on TBINSPECCION.CODCLIENTE = TBCLIENTE.CODCLIENTE
	INNER JOIN TBUSUARIO  ON TBINSPECCION.CODUSUARIOduenio = TBUSUARIO.CODUSUARIO
	INNER JOIN TBUSUARIOCOMPANIAPERFIL  ON TBUSUARIO.CODUSUARIO = TBUSUARIOCOMPANIAPERFIL.CODUSUARIO
	INNER JOIN TBCOMPANIA  ON TBUSUARIOCOMPANIAPERFIL.CODCOMPANIA = TBCOMPANIA.CODCOMPANIA
	INNER JOIN TBPARAMETRO  ON TBINSPECCION.NUMOTIVO = TBPARAMETRO.CODPARAMETRO
	INNER JOIN TBDISTRITO  ON TBINSPECCION.CODDISTRITO = TBDISTRITO.CODDISTRITO
	INNER JOIN TBPROVINCIA  ON TBDISTRITO.CODPROVINCIA = TBPROVINCIA.CODPROVINCIA
	INNER JOIN TBDEPARTAMENTO  ON TBPROVINCIA.CODDEPARTAMENTO = TBDEPARTAMENTO.CODDEPARTAMENTO
	INNER JOIN TBPARAMETRO  ON TBINSPECCION.NUESTADOINSP = TBPARAMETRO.CODPARAMETRO
	LEFT JOIN TBINSPECTORINSPECCION  ON TBINSPECCION.CODINSPECCION = TBINSPECTORINSPECCION.CODINSPECCION
	WHERE (TBINSPECCION.CODINSPECCION = PI_CODINSPECCION OR PI_CODINSPECCION IS NULL OR PI_CODINSPECCION = 0)
	AND (TBUSUARIOCOMPANIAPERFIL.CODCOMPANIA = PI_CODCOMPANIA OR PI_CODCOMPANIA IS NULL OR PI_CODCOMPANIA = 0)
	AND (TBINSPECCION.CODCLIENTE = PI_CODCLIENTE OR PI_CODCLIENTE IS NULL OR PI_CODCLIENTE = 0)
	AND (TBCLIENTE.NUTIPODOCUMENTO = PI_NUTIPODOCUMENTO OR PI_NUTIPODOCUMENTO IS NULL OR PI_NUTIPODOCUMENTO = 0)
	AND (TBCLIENTE.NONUMERODOCUMENTO = PI_NONUMERODOCUMENTO  OR PI_NONUMERODOCUMENTO  IS NULL OR PI_NONUMERODOCUMENTO = '')
	AND (TBCLIENTE.NONOMBRES = PI_NONOMBRES OR PI_NONOMBRES IS NULL OR PI_NONOMBRES = '')
	AND (TBCLIENTE.NOAPELLIDOPATERNO = PI_NOAPELLIDOPATERNO OR PI_NOAPELLIDOPATERNO IS NULL OR PI_NOAPELLIDOPATERNO = '')
	AND (TBINSPECCION.NUMOTIVO = PI_NUMOTIVO OR PI_NUMOTIVO IS NULL OR PI_NUMOTIVO = 0) 
	AND (TBPARAMETRO.NOPARAMETRO = PI_NOMOTIVO OR PI_NOMOTIVO IS NULL OR PI_NOMOTIVO = '')
	AND (TBINSPECCION.NUESTADOINSP = PI_NUESTADOINSP OR PI_NUESTADOINSP IS NULL OR PI_NUESTADOINSP = 0)
	AND (TBINSPECCION.CODDISTRITO = PI_CODDISTRITO OR PI_CODDISTRITO IS NULL OR PI_CODDISTRITO = 0)
	AND (TBINSPECCION.FLESTADO = PI_FLESTADO OR PI_FLESTADO IS NULL OR PI_FLESTADO = 0)
    );

	 PO_CODIGO := '0';
	 PO_MENSAJE := 'Consulta exitosa';
ELSE 
	 PO_CODIGO := '1';
	 PO_MENSAJE := 'No existen datos';
END IF;
END ;
