create or replace NONEDITIONABLE PROCEDURE sp_finalizarinspecciones(
	   PI_NUVISITAS IN TBINSPECCION.NUVISITA%type ,
       PO_CODIGO OUT  VARCHAR,
        PO_MENSAJE OUT  VARCHAR)
as
 cursor c_insepcc is SELECT * FROM TBINSPECCION WHERE NUVISITA > PI_NUVISITAS;
BEGIN 
  for registro in c_insepcc loop
    UPDATE TBINSPECCION
    SET TBINSPECCION.NUESTADOINSP = 20
    WHERE TBINSPECCION.CODINSPECCION = registro.CODINSPECCION AND TBINSPECCION.NUESTADOINSP < 20;

end loop;

 	 PO_CODIGO := '0';
	 PO_MENSAJE := 'Consulta exitosa';
END;
