CREATE OR REPLACE FUNCTION scott.FN_MCD
(N1 NUMBER) RETURN NUMBER
IS
  NDIV NUMBER;
  MCD NUMBER;
BEGIN
  FOR J IN 1 .. N1-1 LOOP
    IF MOD(N1,J)=0 THEN
      MCD := J;
    END IF;
  END LOOP;
  RETURN MCD;
END;
/

SELECT FN_MCD(42) FROM DUAL;