
CREATE OR REPLACE PROCEDURE SCOTT.SP_PARAM_SALIDA
( P_ERROR IN NUMBER, P_VALOR OUT NUMBER)
IS
BEGIN
  P_VALOR := 100;
  IF P_ERROR = 1 THEN
    RAISE NO_DATA_FOUND;
  END IF;
END;
/

SET SERVEROUTPUT ON

-- SIN ERROR

DECLARE
  V_VALOR NUMBER := 1000;
BEGIN
  DBMS_OUTPUT.PUT_LINE( 'VALOR INICIAL: ' || V_VALOR );
  SCOTT.SP_PARAM_SALIDA( 0, V_VALOR );
  DBMS_OUTPUT.PUT_LINE( 'VALOR FINAL: ' || V_VALOR );
END;
/

-- CON ERROR

DECLARE
  V_VALOR NUMBER := 1000;
BEGIN
  DBMS_OUTPUT.PUT_LINE( 'VALOR INICIAL: ' || V_VALOR );
  SCOTT.SP_PARAM_SALIDA( 1, V_VALOR );
  DBMS_OUTPUT.PUT_LINE( 'VALOR FINAL: ' || V_VALOR );
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE( 'VALOR EXCEPTION: ' || V_VALOR );
END;
/

